services:
  - type: web
    name: converge-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
